accounts/urls.py
from django.conf import settings
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm

app_name = 'accounts'



urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login_form.html', authentication_form=LoginForm)
         , name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page=settings.LOGIN_URL), name='logout'),
    path('profile/', views.profile, name='profile'),
]

askdjango/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include

# def root(request):
#     return redirect('blog:post_list')

urlpatterns = [
    # path('', root, name='root'),
    path('', lambda r: redirect('blog:post_list'), name='root'),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('dojo/', include('dojo.urls', namespace='dojo')),
    path('accounts/', include('accounts.urls')),
    path('shop/', include('shop.urls', namespace='shop')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

blog/urls.py
#blog/urls.py
from . import views, views_cbv
from django.urls import path, re_path

app_name = 'blog'

urlpatterns = [
    path('', views_cbv.post_list, name='post_list'),
    re_path(r'^(?P<pk>\d+)/$', views_cbv.post_detail, name='post_detail'),

    path('new/', views.post_new, name='post_new'),
    re_path(r'^(?P<id>\d+)/edit/$', views.post_edit, name='post_edit'),

    path('cbv/new/', views_cbv.post_new),
    re_path(r'^cbv/(?P<pk>\d+)/edit/$', views_cbv.post_edit),
    re_path(r'^cbv/(?P<pk>\d+)/delete/$', views_cbv.post_delete),
]

askdjango/templates/layout.html
{% load static %}
<!doctype html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width-device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no" />
        <title>{% block title %}AskDjango{% endblock %}</title>
        <!-- 기본 bootstrap -->
{#        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />#}
{#        <link rel="stylesheet" href="//stackpath.bootstrapcdn.com/bootswatch/3.3.7/flatly/bootstrap.min.css" />#}
        <link rel="stylesheet" href="//stackpath.bootstrapcdn.com/bootswatch/3.3.7/journal/bootstrap.min.css" />
        <!-- bootstrap: cosmo theme -->
        <!-- <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.7/cosmo/bootstrap.min.css" /> -->
        <!-- <link rel="stylesheet" href="/static/style.css" /> -->
        <link rel="stylesheet" href="{% static "style.css" %}" />
    </head>

    <body>
        <nav class="navbar navbar-default">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">AskDjango</a>
                </div>
                <div id="navbar" class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="{% url "root" %}">Home</a></li>
                        <li><a href="#">About</a></li>
                        <li><a href="#">Contact {{ current_datetime }}</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        {% if not user.is_authenticated %}
                            <li><a href="{% url "accounts:signup" %}">회원가입</a></li>
                            <li><a href="{% url "accounts:login" %}?next={{ request.path }}">로그인</a></li>
                        {% else %}
                            <li><a href="{% url "accounts:profile" %}">프로필</a></li>
                            <li><a href="{% url "accounts:logout" %}?next={{ request.path }}">로그아웃</a></li>
                        {% endif %}

                        <li><a href="#">{{ user.date_joined }}</a></li>
                    </ul>
                </div>
            </div>
        </nav>


        {% if messages %}
            <div class="container">
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        [{{ message.tags }}] {# 메세지 Level #}
                        {{ message.message }} {# 실제 메세지 내용 #}
                    </div>
                {% endfor %}
            </div>
        {% endif %}

        {% block content %}
        {% endblock %}

        <div id="page-footer">
            <div class="container">
                <p class="text-muted">
                    &copy; AskDjango
                    여러분의 파이썬/장고 페이스메이커가 되겠습니다.
                </p>
            </div>
        </div>
    </body>
</html>